### ISSUE TITLE
Issue Tracking

### ISSUE THREAD

**Issue by stekylsha** [stekylsha/CISC210Lab#14]
### Story
As a software developer
I want to issue management
So that I will be able to track defects and enhancement requests.

### Acceptance Criteria
Demonstrate:
- [ ] Understanding of issue tracking
  - [ ] Why? How?
- [ ] Using Github ...
  - [ ] create new bug issue
  - [ ] create new enhancement request issue
- [ ] Coordination between issues, stories, and SCM
